---
# tasks file for ansible-role-modjk

- name: create directory
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - /usr/local/tomcat-connectors

- name: symlink xcode toolchains
  become: yes
  file: src=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain path=/Applications/Xcode.app/Contents/Developer/Toolchains/{{item}} state=link force=yes
  with_items:
    - OSX10.10.xctoolchain
    - OSX10.11.xctoolchain
    - OSX10.12.xctoolchain
    - OSX10.13.xctoolchain

- name: symlink APR
  become: yes
  file: src=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk path=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk state=link force=yes

- name: download tomcat-connectors
  get_url: url=http://apache.belnet.be/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.41-src.tar.gz dest=/usr/local/tomcat-connectors-1.2.41-src.tar.gz mode=0777

- name: extract tomcat-connectors
  unarchive: src=/usr/local/tomcat-connectors-1.2.41-src.tar.gz dest=/usr/local/tomcat-connectors copy=no

- name: configure tomcat-connectors
  command: creates=/usr/local/tomcat-connectors/tomcat-connectors-1.2.41-src/native/config.status chdir=/usr/local/tomcat-connectors/tomcat-connectors-1.2.41-src/native/ ./configure --with-apxs=/usr/sbin/apxs

- name: compile tomcat-connectors
  command: creates=/usr/local/tomcat-connectors/tomcat-connectors-1.2.41-src/native/apache-2.0/mod_jk.so chdir=/usr/local/tomcat-connectors/tomcat-connectors-1.2.41-src/native/ make

- name: activate mod_php
  become: yes
  lineinfile: >
    dest=/etc/apache2/httpd.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    create=true
    insertafter="^#?LoadModule hfs_apple_module"
  with_items:
    - { regexp: '^#?LoadModule jk_module', line: "LoadModule jk_module  /usr/local/tomcat-connectors/tomcat-connectors-1.2.41-src/native/apache-2.0/mod_jk.so" }

- name: configure mod_jk
  become: yes
  copy:
    src: jk.conf
    dest: /etc/apache2/other/jk.conf
